# Generated by Django 4.1.5 on 2023-12-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Cats', 'Cats'), ('Dogs', 'Dogs'), ('Horses', 'Horses')], max_length=16),
        ),
    ]
